[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Packages.composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan optimize:clear"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

