[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan migrate --force || true",
  "php artisan optimize:clear"
]


[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
